- name: Set APT to always use IPv4
  shell: "echo 'Acquire::ForceIPv4 \"true\";' > /etc/apt/apt.conf.d/99force-ipv4"

- name: Enable Routing for IPv4
  sysctl: name="net.ipv4.ip_forward" value=1 sysctl_set=yes state=present reload=yes
  tags:
    - quagga

- name: Install iproute for Quagga dependency
  apt: name=iproute update_cache=yes state=present cache_valid_time=86400

- name: download official quagga deb
  get_url: url=https://s3.amazonaws.com/cumulusfiles/roh-ubuntu1404.tar validate_certs=False dest=/tmp/quagga.tar force=no

- name: Untar the package
  unarchive: src=/tmp/roh-ubuntu1404.tar dest=/tmp/ copy=no

- name: Install Quagga
  apt: deb=/tmp/quagga_0.99.23.1-1+cl3u2_trusty_amd64.deb

- name: copy Quagga daemons
  copy: src=daemons dest=/etc/quagga/

- name: copy Quagga conf
  template: src=Quagga.conf.j2 dest=/etc/quagga/Quagga.conf

- name: reload quagga
  service: name=quagga state=restarted

- name: Force Interfaces Down
  command: ifdown {{item}}
  with_items:
    - lo
    - eth1
    - eth2

- name: Force Interfaces Up
  command: ifup {{item}}
  with_items:
    - lo
    - eth1
    - eth2
