- name: Set APT to always use IPv4
  shell: "echo 'Acquire::ForceIPv4 \"true\";' > /etc/apt/apt.conf.d/99force-ipv4"

- name: Enable Routing for IPv4
  sysctl: name="net.ipv4.ip_forward" value=1 sysctl_set=yes state=present reload=yes
  tags:
    - quagga

- name: Check if iproute is installed
  shell: "dpkg-query -f '${binary:Package}\n' -W"
  register: iproute_installed
  notify: Install iproute for Quagga dependency

- name: Install iproute for Quagga dependency
  apt: name=iproute update_cache=yes state=present cache_valid_time=86400
  when: "'iproute' not in iproute_installed"

- name: download official quagga deb
  #get_url: url=http://repo3.cumulusnetworks.com/repo/pool/cumulus/q/quagga/quagga_0.99.23.1-1+cl3u2_amd64.deb?raw=true dest=/tmp/quagga.deb validate_certs=False
  get_url: url=https://github.com/CumulusNetworks/quagga/blob/cm_2.5/debian/release/quagga_0.99.23.1-1+cl2.5_amd64.deb?raw=true dest=/tmp/quagga.deb validate_certs=False

- name: Install Quagga
  apt: deb=/tmp/quagga.deb

- name: copy Quagga daemons
  copy: src=daemons dest=/etc/quagga/

- name: copy Quagga conf
  template: src=Quagga.conf.j2 dest=/etc/quagga/Quagga.conf

- name: reload quagga
  service: name=quagga state=restarted

- name: Force Interfaces Down
  command: ifdown {{item}}
  with_items:
    - lo
    - eth1
    - eth2

- name: Force Interfaces Up
  command: ifup {{item}}
  with_items:
    - lo
    - eth1
    - eth2